PACKAGE_NAME="kiln-rknpu"
PACKAGE_VERSION="0.9.8"
BUILT_MODULE_NAME[0]="rknpu"
DEST_MODULE_LOCATION[0]="/kernel/drivers/accel/rknpu"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=$kernel_source_dir"
CLEAN="make clean"
